### ISSUE TITLE
gating for rare cell population using flowDensity 2D gating with specifying upper

### ISSUE THREAD

**Issue by anaraserikbek** [RGLab/flowDensity#2]
Hi, 
How can we use flowDensity 2D gating to gate double-positive rare population?
I have tried to gate a rare population (positive for both markers) by using flowDensity's 2D gating as shown in this vignette's Section 4.2 (https://www.bioconductor.org/packages/devel/bioc/vignettes/flowDensity/inst/doc/flowDensityVignette.pdf). Since i cannot use the true marker names (because they contain "-" sign, i used "B+C+" type as was suggested by openCyto's issues.) 
In my gating template i have the following lines: 
MAIT CD8flowdensity	B+C+	LT CD8+	Blue-A-695/40-A,Violet-A-780/60-A	flowDensity	upper=TRUE,use.upper=T,sd.threshold=TRUE,n.sd=1.3,position=c(TRUE,TRUE)				
NKT CD8flowdensity	E+D+	LT CD8+	Violet-E-525/50-A,Violet-A-780/60-A	flowDensity	upper=TRUE,use.upper=T,sd.threshold=TRUE,n.sd=1.3,position=c(TRUE,TRUE)		
**However, i have the following error when using this technique:** 
```
Gating for 'D+'
Error in (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args)  : 
            failed at ALCINA T_AV 10-1974 P3.fcs
          Error in flowDensity::deGate(flow.frame = fr, channel = channel, ...) : 
            unused argument (position = c(TRUE, TRUE))
          In addition: Warning messages:
            1: In rlm.default(x, y, weights, method = method, wt.method = wt.method,  :
                                'rlm' failed to converge in 5 steps
                              2: In singletGate(fr, area = channels[1], height = channels[2], ...) :
                                The IRLS algorithm employed in 'rlm' did not converge.
```
                              
                              
                              
                              **> traceback()**
```
                             ```
 12: stop("failed at ", paste0(sn), "\n", filterRes)
                              11: (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args) 
                              {
                                require(openCyto)
                                sn <- sampleNames(fs)
                                fr <- as(fs, "flowFrame")
                                total <- nrow(fr)
                                subSample <- gFunc_args[["subSample"]]
                                gFunc_args[["subSample"]] <- NULL
                                if (!is.null(subSample)) {
                                  if (is.numeric(subSample)) {
                                    if (subSample > 1) {
                                      samp.ind <- sample.int(total, subSample)
                                      fr <- fr[samp.ind]
                                    }
                                    else if (subSample > 0) {
                                      samp.ind <- sample.int(total, subSample * total)
                                      fr <- fr[samp.ind]
                                    }
                                    else stop("invalid 'subSample' argument: ", subSample)
                                  }
                                  else stop("invalid 'subSample' argument: ", subSample)
                                }
                                openCyto.options <- getOption("openCyto")
                                minEvents <- openCyto.options[["gating"]][["minEvents"]]
                                if (is.null(minEvents)) 
                                  minEvents <- 0
                                if (nrow(fr) <= minEvents) {
                                  warning(paste(sn, collapse = ","), ": Not enough events to proceed the data-driven gating!Returning a dummy gate instead.")
                                  channels <- as.vector(na.omit(channels))
                                  nDim <- length(channels)
                                  if (nDim == 1) 
                                    gate_coordinates <- list(c(-Inf, -Inf))
                                  else if (nDim == 2) 
                                    gate_coordinates <- list(c(-Inf, -Inf), c(-Inf, -Inf))
                                  else stop(nDim, " dimensional gating is not supported yet!")
                                  names(gate_coordinates) <- channels
                                  filterRes <- rectangleGate(gate_coordinates)
                                  if (grepl("flowClust\\.[12]d", gFunc)) 
                                    filterRes <- fcRectangleGate(filterRes, priors = list(), 
                                                                 posts = list())
                                  nPop <- length(popAlias)
                                  filterResType <- ifelse(nPop == 1, "filter", "filters")
                                  if (filterResType == "filters") {
                                    filterRes <- filters(lapply(1:nPop, function(i) filterRes))
                                  }
                                }
                                else {
                                  if (!.isRegistered(gFunc)) {
                                    stop(sprintf("Can't gate using unregistered method %s", 
                                                 gFunc))
                                  }
                                  thisCall <- substitute(f(fr = fr, pp_res = pp_res, channels = channels), 
                                                         list(f = as.symbol(gFunc)))
                                  filterRes <- try(do.call(gFunc, c(list(fr = fr, pp_res = pp_res, 
                                                                         channels = channels), gFunc_args)), silent = TRUE)
                                }
                                if (extends(class(filterRes), "filter") || extends(class(filterRes), 
                                                                                   "filters")) {
                                  list(sapply(sampleNames(fs), function(i) filterRes, simplify = FALSE))
                                }
                                else {
                                  stop("failed at ", paste0(sn), "\n", filterRes)
                                }
                              })(dots[[1L]][[1L]], dots[[2L]][[1L]], gFunc = ".flowDensity", 
                                 popAlias = "D+", channels = "Blue-B-530/30-A", gFunc_args = list(
                                   upper = TRUE, position = c(T, T), positive = TRUE))
                              10: mapply(list(`ALCINA T_AV 10-1974 P3.fcs` = <S4 object of class "ncdfFlowSet">, 
                                              `ALCINA T_CP 09-1946 P2 extempo.fcs` = <S4 object of class "ncdfFlowSet">, 
                                              `ALCINA T_DC 05-1952 P2.fcs` = <S4 object of class "ncdfFlowSet">, 
                                              `ALCINA Treg MAIT_AV 10-1974 P2bis.fcs` = <S4 object of class "ncdfFlowSet">, 
                                              `ALCINA Treg MAIT_BV 08,2f,1966 P3.fcs` = <S4 object of class "ncdfFlowSet">, 
                                              `ALCINA Treg MAIT_CP 09-1946 P1.fcs` = <S4 object of class "ncdfFlowSet">), 
                                         list(`ALCINA T_AV 10-1974 P3.fcs` = NULL, `ALCINA T_CP 09-1946 P2 extempo.fcs` = NULL, 
                                              `ALCINA T_DC 05-1952 P2.fcs` = NULL, `ALCINA Treg MAIT_AV 10-1974 P2bis.fcs` = NULL, 
                                              `ALCINA Treg MAIT_BV 08,2f,1966 P3.fcs` = NULL, `ALCINA Treg MAIT_CP 09-1946 P1.fcs` = NULL), 
                                         FUN = .gating_adaptor, MoreArgs = list(gFunc = ".flowDensity", 
                                                                                popAlias = "D+", channels = "Blue-B-530/30-A", gFunc_args = list(
                                                                                  upper = TRUE, position = c(T, T), positive = TRUE)))
                              9: eval(expr, envir, enclos)
                              8: eval(thisCall)
                              7: .gating_gtMethod(x, y, ...)
                              6: gating(x = this_gate, y, parent = parent, gtPop = gt_node_pop, 
                                        pp_res = pp_res, ...)
                              5: gating(x = this_gate, y, parent = parent, gtPop = gt_node_pop, 
                                        pp_res = pp_res, ...)
                              4: .gating_gatingTemplate(x, y, env_fct, ...)
                              3: .local(x, y, ...)
                              2: gating(gating_template, gs)
                              1: gating(gating_template, gs)

		
```


I have updated to the newest version of flowDensity & i have tried to not use the upper, use.upper parameters & sd.threshold, n.sd parameters, however, i keep receiving this error. 
P.S. also, in the flowDensity vignette mentioned, was the CD27+/CD38+ population identified ONLY by specifying position=c(TRUE,TRUE) without using any other arguments?

**Comment by mikejiang** [comment]
Again, we are not the author or maintainer of this package. It is just one example of how the third-party gating algorithm can be plugged into the `openCyto` framework.

So please try to contact the package author instead.
