### ISSUE TITLE
using flowDensity for 1D gating

### ISSUE THREAD

**Issue by anaraserikbek** [RGLab/flowDensity#3]
When using flowDensity for 1D gating, is there a parameter (as in mindensity) by which you can specify the gate range on the channel? i've seen for many of my 1D gates (when the 2 populations are not completely clearly separated, flowDensity identifies the positive/negatives better), however, there is no parameter to set the range of the gate. I also don't quite understand how to use the "alpha" parameter, how can we calculate this alpha depending on our populations of interest?

**Comment by mikejiang** [comment]
You should probably ask the author of `flowDensity` package.
