### ISSUE TITLE
A peak will never be discovered if it is in the first or last two positions of `dens`

### ISSUE THREAD

**Issue by nicbarker** [RGLab/flowDensity#4]
Hi,
If you take a look at the comparison done on [`/R/helper_functions.R:414`](https://github.com/RGLab/flowDensity/blob/f048454b243b01bc420b5cadb9aab39f2e2cb164/R/helper_functions.R#L414), I believe it will always return null if the single peak is the first element of the `dens` array.

For example, given the following data in `dens`, noting that element `[1]` is the largest,
```R
Browse[4]> dens$y
  [1] 1.906371e-03 1.624343e-03 1.347483e-03 1.085672e-03 8.487902e-04
  [6] 6.448108e-04 4.740793e-04 3.350340e-04 2.261130e-04 1.452183e-04
 [11] 8.810587e-05 4.999520e-05 2.610589e-05 1.212379e-05 5.599970e-06
 [16] 4.551809e-06 6.996681e-06 1.095196e-05 1.474551e-05 1.794717e-05
 [21] 2.043727e-05 2.209613e-05 2.284806e-05 2.279326e-05 2.207590e-05
```

Plotted it looks like this:
<img width="588" alt="screenshot 2017-11-13 13 41 10" src="https://user-images.githubusercontent.com/2264338/32707566-e99271ba-c878-11e7-9f36-09a8dad7888c.png">

The comparison is done as follows:
```R
for (i in 1:(length(d.y)-2*w)) {
    if (d.y[i+w] > d.y[(i+w+1):(i+2*w)] && d.y[i+w] > d.y[i:(i+w-1)] && d.y[i+w] > peak.removal*max(d.y))
}
```

Solved for the first iteration of the loop `i = 1` and the hardcoded value of `w = 1`

```R
for (i in 1:(length(d.y)-2*w)) {
    if (d.y[2] > d.y[(3):(3)] && d.y[2] > d.y[1:(1)] && d.y[2] > peak.removal*max(d.y))
}
```

Note that because of the default value of `w <- 1`, while element `[1]` is never compared directly through iteration, the comparison of `d.y[i+w] > d.y[i:(i+w-1)]` -> `d.y[2] > d.y[1:(1)]`  will prevent element `[2]` from being selected as the peak.

Also because of the way the loop is designed, the last two elements in `dens` will also not be checked:
```R
for (i in 1:(length(d.y)-2*w)) {
```

I'm not sure if there is some reason that the first element is being ignored on purpose, but in my particular case it means that the following error gets thrown when running `flowDensity`:
```R
Error in if (missing(p2) | is.na(p2)) p2 <- min(dens$x) :
  argument is of length zero
In addition: Warning message:
In is.na(p2) : is.na() applied to non-(list or vector) of type 'NULL'
```

traceback():
```R
5: .getIntersect(dens, peaks[i], peaks[i + 1])
4: .densityGating(f = f, channel = channels[2], use.percentile = use.percentile[2],
       percentile = percentile[2], use.upper = use.upper[2], upper = upper[2],
       avg = avg[2], all.cuts = all.cuts[2], sd.threshold = sd.threshold[2],
       n.sd = n.sd[1], alpha = alpha[1], debris.gate = debris.gate[2],
       tinypeak.removal = 1/25)
3: .deGate2D(f = obj, channels = channels, position = position,
       ...)
2: flowDensity(obj = samp, channels = c(1, 14), position = c(TRUE,
       FALSE))
1: flowDensity(obj = samp, channels = c(1, 14), position = c(TRUE,
       FALSE))
```

You can see here that .getIntersect is throwing an error because `peaks` is null, and because of [how R handles comparisons to NULL](https://stackoverflow.com/questions/27350636/r-argument-is-of-length-zero-in-if-statement)

Try this tiny example:
```R
p2 <- NULL
if (missing(p2) | is.na(p2)) print('test')
```

If there isn't any particular reason that the first element is being skipped, it can be fixed by replacing the if statement at `414` with the following:

```R
addPeak <- FALSE
if (i == 1 && d.y[i+w] > d.y[(i+w+1):(i+2*w)] && d.y[i+w] > peak.removal*max(d.y)) {
    addPeak <- TRUE
}
else if (d.y[i+w] > d.y[(i+w+1):(i+2*w)] && d.y[i+w] > d.y[i:(i+w-1)] && d.y[i+w] > peak.removal*max(d.y)) {
    addPeak <- TRUE
}

if (addPeak == TRUE) {
    peaks <- c(peaks, d$x[i+w])
    peaks.ind <- c(peaks.ind, i+w)
}
```

Furthermore, what is the purpose of the `w` parameter? It seems like it may have been intended to protect against lots of small peaks being returned in the case of having some jitter across the density distribution, but the implementation is very strange - the two ranges that it compares:
```R
d.y[i+w] > d.y[(i+w+1):(i+2*w)]
# Value where w = 10 and i = 1
d.y[11] > d.y[(12):(21)]
```
and
```R
d.y[i+w] > d.y[i:(i+w-1)]
# Value where w = 10 and i = 1
d.y[11] > d.y[1:10]
```

Clips off all the values that are `< w` and `> length - 2 * w` (i.e you lose twice as much data off the end of `dens` that you do off the front, was this intended to be implemented this way?

**Comment by mikejiang** [comment]
please repost it  here https://github.com/mehrnoushmalek/flowDensity

**Comment by nicbarker** [comment]
Thanks Mike didn't realise it was a forked repo.

**Comment by nicbarker** [comment]
New issue is here: https://github.com/mehrnoushmalek/flowDensity/issues/2
