### ISSUE TITLE
singlet.gate doesn't seem to be mentioned anywhere except the docs

### ISSUE THREAD

**Issue by nicbarker** [RGLab/flowDensity#5]
Hi,
In the vignettes, there is an example that mentions the following:
```R
sglt <- flowDensity(obj=lymph, singlet.gate=TRUE)
```
On my machine, this throws an error:

```R
> sglt <- flowDensity(obj=lymph, singlet.gate=TRUE)
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘flowDensity’ for signature ‘"CellPopulation", "missing", "missing", "missing"’
```

When I grep the codebase, there doesn't seem to be any mention of `singlet.gate` except for in the documentation.

Is there something I'm missing here?

**Comment by mikejiang** [comment]
This is actually a forked repo. Can you repost your issue at its maintainer's repo site to get better assistance? https://github.com/mehrnoushmalek/flowDensity

**Comment by nicbarker** [comment]
Hi Mike, thanks for the heads up, I didn't realise.

**Comment by nicbarker** [comment]
If you're interested in following the new issue is here:
https://github.com/mehrnoushmalek/flowDensity/issues/1
