### ISSUE TITLE
Obtaining a flowframe

### ISSUE THREAD

**Issue by fbenedett** [RGLab/flowDensity#6]
Hello.

I would like to use flowDensity to automatically gate several fcs files.
I see that in the guide you provide an example:
> sngl <- flowDensity(f,channels = c("FSC-A","FSC-H"),position = c(F,F),+                     percentile =c(.99999,.99999),use.percentile = c(T,T), ellip.gate = T,scale = .99 )
> plotDens(f,c(1,2))> lines(sngl@filter,type="l")
> bcell <- flowDensity(sngl, channels=c(9, 3), position=c(FALSE, NA))
> plot(getflowFrame(sngl), bcell)

but, for my understanding, sngl is not a flow frame.
Is there a way to obtain a gated flow frame?

Imagine also that you would like to gate for a distribution like the one in the image.
Is there a way to do it with flowDensity?
![Screenshot from 2019-06-11 17-59-58](https://user-images.githubusercontent.com/11632090/59287926-f4a31680-8c72-11e9-8414-d8055630b959.png)

**Comment by SamGG** [comment]
Hi,
a) getflowFrame returns a flowFrame; look at the example of this function.
b) take a look at http://opencyto.org
HTH

**Comment by mikejiang** [comment]
also https://bioconductor.org/packages/release/bioc/vignettes/openCyto/inst/doc/HowToAutoGating.html

**Comment by fbenedett** [comment]
Thank you.
